### ISSUE TITLE
Support MQTT retained messages semantics.

### ISSUE THREAD

**Issue by Technoboy-** [streamnative/mop#250]
## Motivation
Currently, MoP does not support MQTT retained messages semantics. We should support this at broker side.

## Implementation
A short description about this implementation in MoP cluster:
![image](https://user-images.githubusercontent.com/6297296/162345992-2dfbbdc6-15ea-47bf-88f5-5bf629d04436.png)

We will use the system topic introduced by #560  to support this feature.
When user1 sends out a retained msg, suppose the proxy will transfer it to mop-broker1. Then mop-broker1 will send out a system event, all other broker nodes will receive this event by the internal reader and store it in the memory.
Then user2 connects to broker2 and subscribes to a topic that matches the retained topic, broker2 could send back the retained msg in the memory immediately.

**Comment by AngusLean** [comment]
I will try to work on it recently。

**Comment by tsturzl** [comment]
We recently started using MoP as a way to connect IoT devices into Pulsar, and retain is something we've historically used a lot for a variety of reasons. We're currently working around this at the application level, but this feature would be really useful. I have put some thought into it and I'm kind of at a loss as how it could be efficiently implemented. Pulsar doesn't seem to behave like Kafka does where you can just consume from the latest and step back one. It seems like Pulsar is really only capable of easily moving forward.

I'm wondering if anyone has thought about a solution to this and what that might be. I'm also curious how this is being planned as I assume this will only work on persistent topics which have retain policies on them since pulsar by default deletes acknowledged messages.

**Comment by Technoboy-** [comment]
> We recently started using MoP as a way to connect IoT devices into Pulsar, and retain is something we've historically used a lot for a variety of reasons. We're currently working around this at the application level, but this feature would be really useful. I have put some thought into it and I'm kind of at a loss as how it could be efficiently implemented. Pulsar doesn't seem to behave like Kafka does where you can just consume from the latest and step back one. It seems like Pulsar is really only capable of easily moving forward.
> 
> I'm wondering if anyone has thought about a solution to this and what that might be. I'm also curious how this is being planned as I assume this will only work on persistent topics which have retain policies on them since pulsar by default deletes acknowledged messages.

Hi @tsturzl , I have shortened describe this implementation on this issue. Please check and if you have any questions, just let me know.

**Comment by tsturzl** [comment]
@Technoboy- Ah this looks great! I had briefly thought of something similar, but it seemed like it would be a lot of work, but it seems like you already have a system topic. I assume when brokers reconnect after an outage or maintenance that the mop broker can replay the system topic to rebuild it's retained messages? I assume that's the reason for using a reader. Awesome work! I'm glad to see the quick turn around.
