### ISSUE TITLE
Readme.md states "only MQTT 3.1.1 supported" but code base seems to indicate MQTT 5 is also supported

### ISSUE THREAD

**Issue by edlane** [streamnative/mop#933]
**Describe the bug**
Readme.md states "only MQTT 3.1.1 supported" but code base seems to indicate MQTT 5 is also supported

**To Reproduce**
1. Go to ['Readme.md'](https://github.com/streamnative/mop/blob/master/README.md)
2. reconcile this with the tests found here: https://github.com/streamnative/mop/tree/master/tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq

**Expected behavior**
not sure from reading the Readme.md which versions of MQTT are actually supported

Please explain or fix -- thanks

**Comment by tsturzl** [comment]
I'm not a maintainer so I can't speak definitively, but if you're looking at the main line you're seeing the current effort to support MQTT 5. I wouldn't be surprised if there are some MQTT 5 features that have landed in releases too, because some MQTT 5 spec differences only impact the broker and thus don't require a full working MQTT 5 implementation. There is an ongoing ticket to support MQTT 5, and that work is all in main line. The README on main is tracking what users expect to see, so it's still saying 3.1.1 support only, which is largely still true. I cannot speak to the timeline of these features, or whether or not certain MQTT 5 features have been pushed out in any releases. But as far as I know there is no MQTT 5 support in any release, and the effort in on going to support it.
